version: '3.3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: ./nginx/Dockerfile
    ports:
    - 8080:80
    volumes:
      - type: bind
        source: .
        target: /app

  php-fpm:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "54321:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
